import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { MAP_VIEWBOX, REGION_CENTRES, REGION_PATHS } from "@/lib/map/regions";
import { REGIONS } from "@/lib/genesis";
import { home as ko } from "@/content/ko/home";
import { home as en } from "@/content/en/home";

/**
 * The region map.
 *
 * `lib/map/regions.ts` is generated by `scripts/build-map.mjs` from the KOSTAT
 * boundaries and committed. Generated files are the ones nobody reads, so this
 * checks the properties the drawing depends on rather than the bytes: a shape
 * for every region the form offers, a label anchor inside the frame, and no
 * region quietly simplified down to a triangle.
 */

const [, , boxW, boxH] = MAP_VIEWBOX.split(" ").map(Number);

describe("the generated boundaries", () => {
  it("frames the peninsula portrait, north up", () => {
    expect(boxW).toBeGreaterThan(50);
    expect(boxH).toBeGreaterThan(50);
    // Korea is taller than it is wide. A flipped or transposed projection is
    // the failure that would otherwise look plausible in a diff.
    expect(boxW / boxH).toBeLessThan(1.4);
  });

  it("draws every region the form asks about", () => {
    for (const region of REGIONS) {
      const d = REGION_PATHS[region.id];
      expect(d, `${region.id} has no path`).toBeTruthy();
      expect(d.startsWith("M"), `${region.id} is not a path`).toBe(true);

      /*
       * Counted in points, not characters.
       *
       * The first run of the generator collapsed every closed ring to its two
       * endpoints — Gangwon came out as a single straight line — and the file
       * still parsed, still rendered, and still looked like a map in a diff.
       * Twelve is the floor because Jeju legitimately needs far fewer points
       * than the mainland: it is one smooth island, and a threshold set by the
       * south-west archipelago would fail it for being the right shape.
       */
      const points = (d.match(/[ML]/g) ?? []).length;
      expect(points, `${region.id} collapsed to ${points} points`).toBeGreaterThanOrEqual(12);
    }
  });

  it("puts every label anchor inside the frame", () => {
    for (const region of REGIONS) {
      const centre = REGION_CENTRES[region.id];
      expect(centre, `${region.id} has no centre`).toBeTruthy();
      const [x, y] = centre;
      expect(x, `${region.id} anchor is off the frame`).toBeGreaterThan(0);
      expect(x).toBeLessThan(boxW);
      expect(y).toBeGreaterThan(0);
      expect(y).toBeLessThan(boxH);
    }
  });

  it("keeps Jeju south of the mainland regions", () => {
    // A projection sign error would put the island at the top and nothing else
    // in this file would notice.
    const jeju = REGION_CENTRES.jeju[1];
    for (const region of REGIONS.filter((r) => r.id !== "jeju")) {
      expect(jeju, `jeju is not south of ${region.id}`).toBeGreaterThan(
        REGION_CENTRES[region.id][1],
      );
    }
  });
});

/**
 * The caption has to describe the drawing it captions.
 *
 * It stopped doing so the moment the map became real: the note still opened
 * with "not a real map, a schematic", which had been an honest defence of seven
 * hand-drawn blobs and became a false statement about actual boundaries the
 * instant they landed. The commit that changed the picture left the sentence
 * alone, and the site spent a deploy misdescribing its own map.
 */
describe("the caption", () => {
  it("no longer calls the map a schematic", () => {
    expect(ko.density.note).not.toContain("도식");
    expect(en.density.note.toLowerCase()).not.toContain("schematic");
  });

  it("still says the resolution stops at the region", () => {
    // The honest half of the old note, which must survive the correction:
    // registrants give a region and never a coordinate.
    expect(ko.density.note).toContain("좌표");
    expect(en.density.note.toLowerCase()).toContain("coordinates");
  });
});

/**
 * The fallback has to be reachable.
 *
 * `.rmap__fail` and its copy existed from the start and never once rendered.
 * MapLibre raises GPUInitializationError from inside the Map constructor and
 * fires it as an `error` event; `map.on("error", …)` is necessarily attached
 * after that constructor returns, so nothing was listening and nothing threw.
 * Every reader without WebGL2 — hardware acceleration off, an older phone, a
 * locked-down work laptop — got an unexplained black rectangle.
 *
 * Verified in a headless browser launched with --disable-gpu: before the
 * probe, `.rmap__fail` was absent and a dead canvas was present; after it, the
 * message renders and no canvas is built.
 *
 * Asserted against the source because the failure is an ordering mistake, and
 * a component test with a working WebGL2 context passes either way.
 */
describe("the route map when the browser cannot draw it", () => {
  const source = readFileSync("components/community/route-map.tsx", "utf8");

  it("asks about WebGL2 before constructing the map", () => {
    const probe = source.indexOf('getContext("webgl2")');
    const construct = source.indexOf("new maplibre.Map(");
    expect(probe, "no WebGL2 probe — the fallback is unreachable again").toBeGreaterThan(-1);
    expect(
      probe,
      "the probe must run before the constructor, or MapLibre fires its error with nobody listening",
    ).toBeLessThan(construct);
  });

  it("still shows the fallback copy it was given", () => {
    expect(source).toContain("rmap__fail");
    expect(ko.routes.failed.length).toBeGreaterThan(0);
    expect(en.routes.failed.length).toBeGreaterThan(0);
  });
});
