/**
 * The public half of the key Tesla registers on vehicles.
 *
 * Fleet API will not treat an application as registered unless a PEM-encoded EC
 * public key on the secp256r1 (prime256v1) curve is reachable at
 *
 *     https://teslam.io/.well-known/appspecific/com.tesla.3p.public-key.pem
 *
 * and Tesla's own wording is that it "must be and remain hosted" there. Remain
 * is the word that decides how this is stored. A file fetched from an object
 * store, or read from disk at request time, can go missing on a day nobody is
 * looking, and the failure is not a 404 anybody notices — it is Fleet API
 * quietly answering that the application is not registered, and vehicles
 * declining to stream.
 *
 * So the key lives in this file, in the repository, as a string. It is public
 * by definition: Tesla puts it on cars and shows the domain to owners during
 * pairing. The private half is generated by `scripts/tesla/keypair.mjs`, which
 * writes it outside the working tree and never anywhere near here.
 *
 * `null` until the pair is generated, and the route serves 404 while it is —
 * an empty response with a 200 would register an empty key.
 */
export const TESLA_PUBLIC_KEY_PEM: string | null = null;

/**
 * Whether a string looks like the key Tesla asked for.
 *
 * Not a substitute for `GET /api/1/partner_accounts/public_key?domain=`, which
 * is the only check that speaks for Tesla. This one catches the mistakes that
 * happen on this side: the private key pasted in by accident, a PKCS#1 RSA key
 * from a different `openssl` invocation, or a file that got truncated.
 */
export function looksLikeTeslaPublicKey(pem: string): boolean {
  const body = pem.trim();
  if (body.includes("PRIVATE KEY")) return false;
  if (!body.startsWith("-----BEGIN PUBLIC KEY-----")) return false;
  if (!body.endsWith("-----END PUBLIC KEY-----")) return false;
  // A P-256 SubjectPublicKeyInfo is 91 bytes, which is 124 base64 characters
  // over two lines. Anything much shorter is not a key and anything much longer
  // is a different curve or a different algorithm.
  const base64 = body
    .split("\n")
    .filter((line) => !line.startsWith("-----"))
    .join("");
  return base64.length > 100 && base64.length < 200;
}

/** Where Tesla looks. Written once so the route and the tests cannot disagree. */
export const TESLA_PUBLIC_KEY_PATH = "/.well-known/appspecific/com.tesla.3p.public-key.pem";
